In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_csv("../data/recruitment_mydata.csv")
df

,Age,Gender,EducationLevel,ExperienceYears,PreviousCompanies,DistanceFromCompany,InterviewScore,SkillScore,PersonalityScore,RecruitmentStrategy,HiringDecision
0,26.0,Female,Bachelor's (Type 2),0.0,3,26.783828,48.0,78.0,91.0,Aggressive,1
1,39.0,Female,PhD,12.0,3,25.862694,35.0,68.0,80.0,Moderate,1
2,48.0,Male,Bachelor's (Type 2),3.0,2,9.920805,20.0,67.0,13.0,Moderate,0
3,34.0,Female,Bachelor's (Type 2),5.0,2,6.407751,36.0,27.0,70.0,Conservative,0
4,30.0,Male,Bachelor's (Type 1),6.0,1,43.105343,23.0,52.0,85.0,Moderate,0
...,...,...,...,...,...,...,...,...,...,...,...
1495,48.0,Male,Bachelor's (Type 2),3.0,4,9.183783,66.0,3.0,80.0,Conservative,1
1496,27.0,Female,Bachelor's (Type 2),10.0,3,14.847731,43.0,97.0,7.0,Moderate,0
1497,24.0,Female,Bachelor's (Type 1),1.0,2,4.289911,31.0,91.0,58.0,Aggressive,1
1498,48.0,Male,Bachelor's (Type 2),4.0,4,36.299263,9.0,37.0,44.0,Moderate,1
1499,34.0,Female,Bachelor's (Type 2),11.0,5,12.910472,63.0,40.0,26.0,Moderate,1

In [19]:
df.head()

,Age,Gender,EducationLevel,ExperienceYears,PreviousCompanies,DistanceFromCompany,InterviewScore,SkillScore,PersonalityScore,RecruitmentStrategy,HiringDecision
0,26.0,Female,Bachelor's (Type 2),0.0,3,26.783828,48.0,78.0,91.0,Aggressive,1
1,39.0,Female,PhD,12.0,3,25.862694,35.0,68.0,80.0,Moderate,1
2,48.0,Male,Bachelor's (Type 2),3.0,2,9.920805,20.0,67.0,13.0,Moderate,0
3,34.0,Female,Bachelor's (Type 2),5.0,2,6.407751,36.0,27.0,70.0,Conservative,0
4,30.0,Male,Bachelor's (Type 1),6.0,1,43.105343,23.0,52.0,85.0,Moderate,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  1499 non-null   float64
 1   Gender               1500 non-null   object
 2   EducationLevel       1499 non-null   object
 3   ExperienceYears      1499 non-null   float64
 4   PreviousCompanies    1500 non-null   int64
 5   DistanceFromCompany  1500 non-null   float64
 6   InterviewScore       1499 non-null   float64
 7   SkillScore           1499 non-null   float64
 8   PersonalityScore     1499 non-null   float64
 9   RecruitmentStrategy  1499 non-null   object
 10  HiringDecision       1500 non-null   int64
dtypes: float64(6), int64(2), object(3)
memory usage: 129.0+ KB

In [29]:
df.isnull().sum()

Age                    0
Gender                 0
EducationLevel         0
ExperienceYears        0
PreviousCompanies      0
DistanceFromCompany    0
InterviewScore         0
SkillScore             0
PersonalityScore       0
RecruitmentStrategy    0
HiringDecision         0
dtype: int64

In [24]:
df = df.drop_duplicates()

In [27]:
# FILL NULL VALUES
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna('Unknown')

for col in df.select_dtypes(include=['int64','float64']).columns:
    df[col] = df[col].fillna(df[col].median())

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  1500 non-null   float64
 1   Gender               1500 non-null   object
 2   EducationLevel       1500 non-null   object
 3   ExperienceYears      1500 non-null   float64
 4   PreviousCompanies    1500 non-null   int64
 5   DistanceFromCompany  1500 non-null   float64
 6   InterviewScore       1500 non-null   float64
 7   SkillScore           1500 non-null   float64
 8   PersonalityScore     1500 non-null   float64
 9   RecruitmentStrategy  1500 non-null   object
 10  HiringDecision       1500 non-null   int64
dtypes: float64(6), int64(2), object(3)
memory usage: 129.0+ KB

In [30]:
df.to_csv(
    "../cleaned_data/cleaned_recruitment_data.csv",
    index=False
)

In [31]:
df.describe()

,Age,ExperienceYears,PreviousCompanies,DistanceFromCompany,InterviewScore,SkillScore,PersonalityScore,HiringDecision
count,1500.000000,1500.000000,1500.00000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,35.140667,7.693333,3.00200,25.505379,50.586667,51.126000,49.374000,0.310000
std,9.247661,4.641298,1.41067,14.567151,28.613872,29.351646,29.348828,0.462647
min,20.000000,0.000000,1.00000,1.031376,0.000000,0.000000,0.000000,0.000000
25%,27.000000,4.000000,2.00000,12.838851,25.000000,25.750000,23.000000,0.000000
50%,35.000000,8.000000,3.00000,25.502239,52.000000,53.000000,49.000000,0.000000
75%,43.000000,12.000000,4.00000,37.737996,75.000000,76.000000,76.000000,1.000000
max,50.000000,15.000000,5.00000,50.992462,100.000000,100.000000,100.000000,1.000000

In [32]:
df.columns

Index(['Age', 'Gender', 'EducationLevel', 'ExperienceYears',
       'PreviousCompanies', 'DistanceFromCompany', 'InterviewScore',
       'SkillScore', 'PersonalityScore', 'RecruitmentStrategy',
       'HiringDecision'],
      dtype='object')